import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "...@/styles/Home.module.css";
import Script from "next/script";
// import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // const [todo, setTodo] = useState(null);

  // const getTodo = async () => {
  //   const res = await fetch(
  //     "http://127.0.0.1:8090/api/collections/todolist/records"
  //   );
  //   const data = await res.json();

  //   setTodo(data);
  //   console.log(data);
  // };

  return (
    <>
      <Head>
        <title>DailyApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
          crossorigin="anonymous"
        ></link>
      </Head>
      {/* <button onClick={getTodo}>Projek Kelompok 1</button>
      {todo && todo.items.map((todo) => <h2>{todo.judulrencana}</h2>)} */}
      <div className={`${styles.bg}`}>
        <div className="container">
          <div className="row ">
            <div className="col-md-6 mt-1">
              <img src="LOGO.png" alt="" width="45px" />
            </div>
            <div className="col-md-6 mt-1 ">
              <button type="button " class="btn text-white">
                Home
              </button>
              <button type="button" class="btn text-white">
                Profile
              </button>
              <button type="button" href="{/signup}" class="btn text-white">
                Sign Up
              </button>
            </div>
          </div>
        </div>
        <div className="container">
          <div className="row justify-content-center mt-5">
            <div className="col-md-5">
              <h1 className="text-white display-2">Make Your</h1>
              <h1 className="text-white display-2">Planing</h1>
              <h4 className="text-white display-6">You can write and list</h4>
              <h4 className="text-white display-6">What you like</h4>
            </div>
            <div className="col-md-5">
              <img src="kalender.jpg" alt="" width="350px" />
            </div>
          </div>
        </div>
        <div className="container mt-5 ">
          <div className="row d-flex justify-content-center">
            <div class=" col-1 ">
              <button type="button" class="btn border text-white">
                Login
              </button>
            </div>
            <div class=" col-2">
              <button type="button" class="btn border text-white">
                Get Started
              </button>
            </div>
          </div>
        </div>
      </div>
      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"
      />
    </>
  );
}
